config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  resources :primes, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :documents
  resources :notifications
  resources :properties
  resources :projects
  resources :referrals
  resources :requests
  resources :simulations
  resources :users
  resources :work

  # config/routes.rb
  post "/calcul-categorie", to: "categories#calcul"
  get '/admin/dashboard', to: 'admin#dashboard'
  get '/localstorage', to: 'localstorage#index'

  namespace :api do
    post 'save_localstorage', to: 'localstorage#save'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :primes

  validates :code, :description, presence: true
  validates :code, uniqueness: true
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  belongs_to :property, optional: true
  belongs_to :request, optional: true
  belongs_to :project, optional: true
  belongs_to :simulation, optional: true

  validates :file_url, :type_document, presence: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user

  validates :message, :type, presence: true
end

app/models/prime.rb
class Prime < ApplicationRecord
  belongs_to :category
  has_many :simulation_prime_cards
  has_many :simulations, through: :simulation_prime_cards
  has_many :works
  has_many :request_progresses

  validates :slug, :titre, presence: true
  validates :slug, uniqueness: true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  belongs_to :property, optional: true
  belongs_to :request, optional: true
  has_many :works
  has_many :documents

  validates :nom, presence: true
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_many :simulations
  has_many :projects
  has_many :requests
  has_many :documents

  validates :address, :type_bien, presence: true
end

app/models/referral.rb
class Referral < ApplicationRecord
  belongs_to :user

  validates :email_ami, presence: true
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :property
  belongs_to :project
  belongs_to :simulation, optional: true

  has_many :request_progresses
  has_many :documents

  validates :status, presence: true
end

app/models/request_progress.rb
class RequestProgress < ApplicationRecord
  belongs_to :request
  belongs_to :prime

  validates :step, :pourcentage, presence: true
end

app/models/simulation.rb
class Simulation < ApplicationRecord
  belongs_to :user
  belongs_to :property, optional: true
  has_many :simulation_prime_cards, dependent: :destroy
  has_many :primes, through: :simulation_prime_cards
  has_many :documents

  has_one :request

  validates :region, :titre, :source, presence: true
end

app/models/simulation_prime_card.rb
class SimulationPrimeCard < ApplicationRecord
  belongs_to :simulation
  belongs_to :prime

  validates :prime_id, uniqueness: { scope: :simulation_id }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :simulations
  has_many :properties
  has_many :projects
  has_many :requests
  has_many :referrals
  has_many :notifications
  has_many :documents

  belongs_to :last_active_simulation, class_name: "Simulation", optional: true

  validates :email, presence: true, uniqueness: true
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :project
  belongs_to :prime

  validates :surface, :montant_estimé, presence: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def dashboard
    @local_storage_data = {} # Placeholder pour les données JS
    @primes = Prime.all
    @categories = Category.all
    @documents = Document.all
    @notifications = Notification.all
    @properties = Property.all
    @projects = Project.all
    @referrals = Referral.all
    @requests = Request.all
    @simulations = Simulation.all
    @users = User.all
    @work = Work.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

   def calcul
    profil = {
      revenu_annuel: params[:revenu_annuel].to_f,
      statut: params[:statut],
      personnes_a_charge: params[:personnes_a_charge].to_i,
      autre_bien: params[:autre_bien] == "true",
      woonmaatschappij: params[:woonmaatschappij] == "true"
    }

    categorie = Categorie.calculer_depuis(profil)
    render json: categorie
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @primes = Prime.all
    @categorie_id = 3 # ou toute logique que tu veux pour déterminer la catégorie en front
    @plafonds_par_categorie = Prime.group(:category_id).maximum(:plafond)
    @groupes_plafond = Prime.distinct.pluck(:groupe)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/controllers/work_controller.rb
class WorkController < ApplicationController
  def index
    @work = Work.all
  end

  def show
    @work_item = Work.find(params[:id])
  end

  def new
    @work_item = Work.new
  end

  def create
    @work_item = Work.new(work_params)
    if @work_item.save
      redirect_to @work_item
    else
      render :new
    end
  end

  def edit
    @work_item = Work.find(params[:id])
  end

  def update
    @work_item = Work.find(params[:id])
    if @work_item.update(work_params)
      redirect_to @work_item
    else
      render :edit
    end
  end

  def destroy
    @work_item = Work.find(params[:id])
    @work_item.destroy
    redirect_to work_index_path
  end

  private

  def work_params
    params.require(:work).permit(:title, :description, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/primes_helper.rb
module PrimesHelper
end

app/views/categories/index.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Catégories de revenus</h1>

  <div class="row">
    <% @categories.each do |category| %>
      <div class="col-md-6">
        <div class="card mb-4 shadow-sm">
          <div class="card-body">
            <h5 class="card-title"><%= category.description %></h5>
            <p class="card-text">
              Code : <strong><%= category.code %></strong><br>
              Seuil seul : <%= number_with_delimiter(category.seuil_seul) %> €<br>
              Seuil avec charge : <%= number_with_delimiter(category.seuil_seul_avec_charge) %> €<br>
              + <%= number_with_delimiter(category.increment_par_personne) %> € par personne en plus
            </p>
            <%= link_to "Détails", category_path(category), class: "btn btn-primary btn-sm" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="d-flex justify-content-center gap-3 mt-4">
    <%= link_to "← Retour à l'accueil", root_path, class: "btn btn-outline-secondary" %>
  </div>

app/views/categories/show.html.erb
<div class="container mt-5">
  <h1 class="mb-3">Détails de la catégorie : <%= @category.description %></h1>

  <table class="table table-bordered">
    <tbody>
      <tr>
        <th scope="row">Code</th>
        <td><%= @category.code %></td>
      </tr>
      <tr>
        <th scope="row">Seuil seul</th>
        <td><%= number_with_delimiter(@category.seuil_seul) %> €</td>
      </tr>
      <tr>
        <th scope="row">Seuil seul avec charge</th>
        <td><%= number_with_delimiter(@category.seuil_seul_avec_charge) %> €</td>
      </tr>
      <tr>
        <th scope="row">Couple sans charge</th>
        <td><%= number_with_delimiter(@category.couple_sans_charge) %> €</td>
      </tr>
      <tr>
        <th scope="row">Par personne en plus</th>
        <td><%= number_with_delimiter(@category.increment_par_personne) %> €</td>
      </tr>
      <tr>
        <th scope="row">Autre bien autorisé ?</th>
        <td><%= @category.autre_bien_interdit ? "Non" : "Oui" %></td>
      </tr>
      <tr>
        <th scope="row">Location sociale autorisée ?</th>
        <td><%= @category.location_sociale_autorisee ? "Oui" : "Non" %></td>
      </tr>
      <tr>
        <th scope="row">Éligible à la Verbouwlening ?</th>
        <td><%= @category.eligible_pour_verbouwlening ? "Oui" : "Non" %></td>
      </tr>
    </tbody>
  </table>
</div>

<div class="d-flex justify-content-center gap-3 mt-4">
  <%= link_to "← Retour à la liste", categories_path, class: "btn btn-secondary" %>
  <%= link_to "Accueil", root_path, class: "btn btn-outline-primary" %>
</div>